### ISSUE TITLE
Cannot run due to missing modules

### ISSUE THREAD

**Issue by joesepi** [maximilien/ghtrack#15]
### Bug report

I'm getting module not found errors. See below

### Expected behavior

Install and run ghtrack

### Steps to reproduce the problem

Install and run ghtrack (on my machine?)

### ./ght version

```
➜  ghtrack git:(master) ./ght version
Traceback (most recent call last):
  File "/Users/joesepi/code/ghtrack/./ghtrack.py", line 65, in <module>
    from cli import *
  File "/Users/joesepi/code/ghtrack/cli.py", line 15, in <module>
    import io, sys, yaml, json, csv, os.path
ModuleNotFoundError: No module named 'yaml'
```

### Python version

> add output of python --version

```
➜  ghtrack git:(master) python --version
zsh: command not found: python
➜  ghtrack git:(master) python3 --version
Python 3.11.5
```

### More output from my issue

```
➜  ghtrack git:(master) ./ght --help
Traceback (most recent call last):
  File "/Users/joesepi/code/ghtrack/./ghtrack.py", line 64, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
➜  ghtrack git:(master) pip3 install docopt
Collecting docopt
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: docopt
  Building wheel for docopt (pyproject.toml) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13705 sha256=ebca8400d58cfd5103868c421e8539cda4694d6b95bac7703ace678fd40af17c
  Stored in directory: /Users/joesepi/Library/Caches/pip/wheels/1a/b0/8c/4b75c4116c31f83c8f9f047231251e13cc74481cca4a78a9ce
Successfully built docopt
Installing collected packages: docopt
Successfully installed docopt-0.6.2
➜  ghtrack git:(master) ./ght --help                                                                                                        
Traceback (most recent call last):
  File "/Users/joesepi/code/ghtrack/./ghtrack.py", line 65, in <module>
    from cli import *
  File "/Users/joesepi/code/ghtrack/cli.py", line 15, in <module>
    import io, sys, yaml, json, csv, os.path
ModuleNotFoundError: No module named 'yaml'
```

**Comment by maximilien** [comment]
Did you follow: [environment](https://github.com/maximilien/ghtrack#environment)

**Comment by joesepi** [comment]
I didn't. Closing issue. My bad.
